services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/certs
    depends_on:
      - moodle
    networks:
      - moodle_network

  moodle:
    image: bitnami/moodle:4.1.5
    container_name: moodle
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_SITE_URL=https://your-domain.com
      - MOODLE_EXTRA_CONFIG_CONTENT=
        $CFG->session_handler_class = '\\core\\session\\redis';
        $CFG->session_redis_host = 'redis';
        $CFG->session_redis_port = 6379;
        $CFG->session_redis_password = 'redispass';
        $CFG->session_redis_prefix = 'moodle_prod_';
        $CFG->cachestore_redis_server = 'redis';
        $CFG->cachestore_redis_port = 6379;
        $CFG->cachestore_redis_password = 'redispass';
      - BITNAMI_DEBUG=false
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_moodledata:/bitnami/moodledata
    depends_on:
      - postgres
      - redis
    expose:
      - "8080"
    networks:
      - moodle_network

  postgres:
    image: percona/percona-distribution-postgresql:15
    container_name: postgres
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodlepass
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      PMM_AGENT_SERVER_ADDRESS: pmm-server
      PMM_AGENT_SERVER_USERNAME: admin
      PMM_AGENT_SERVER_PASSWORD: admin
      PMM_AGENT_SERVER_INSECURE_TLS: "1"
      PMM_AGENT_SETUP: "yes"
      PMM_AGENT_CONFIG: "yes"
      PMM_AGENT_PRERUN_SCRIPT: "psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS pg_stat_statements;'"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/conf.d/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moodle_network

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - moodle_network

  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    restart: always
    ports:
      - '8083:80'  # Expose PMM Server web interface on port 8083
    volumes:
      - pmm-data:/srv  # Data persistence for PMM Server
    environment:
      - PMM_SERVER_ADMIN_USER=admin
      - PMM_SERVER_ADMIN_PASSWORD=admin
    networks:
      - moodle_network

networks:
  moodle_network:

volumes:
  postgres_data:
  redis_data:
  moodle_data:
  moodle_moodledata:
  pmm-data:
